// Use relative paths so they work under GitHub Pages sub-paths without leading slash.
// Updated: Banner assets added

export const ASSETS = {
  // Removed legacy FTP_DICE_ROLL_1 and FTP_DICE_ROLL_2 in favor of PAGE 1 and PAGE 2 layered intro assets
  FTP_DICE_ROLL_1: 'FTP_DICE_ROLL_1.png',
  FTP_DICE_ROLL_2: 'FTP_DICE_ROLL_2.png',
  FTP_INSTANT_WIN: 'FTP_INSTANT_WIN.png',
  FTP_INSTANT_WIN_SPIN: 'FTP_INSTANT_WIN_SPIN.png',
  FTP_INSTANT_WIN_PRIZE: 'FTP_INSTANT_WIN_PRIZE.png',
  FTP_FINISH_1: 'FTP_FINISH_1.png',
  FTP_FINISH_2: 'FTP_FINISH_2.png',
  FTP_FINISH_3: 'FTP_FINISH_3.png',
  // PAGE 1 assets for new intro scene
  // (removed old PAGE 1/ and PAGE 2/ keys, now using lowercase)
  INTRO_BG: 'page1/BACKGROUND.png',
  INTRO_1: 'page1/1.png',
  INTRO_2: 'page1/2.png',
  INTRO_3: 'page1/3.png',
  INTRO_4: 'page1/4.png',
  INTRO_5: 'page1/5.png',
  INTRO_6: 'page1/6.png',
  INTRO_7: 'page1/7.png',
  INTRO_8: 'page1/8.png',
  INTRO_9: 'page1/9.png',
  INTRO_10: 'page1/10.png',
  INTRO2_BG: 'page2/BACKGROUND2.png',
  INTRO2_TOP_BANNER: 'page2/TOP_BANNER.png',
  INTRO2_1: 'page2/1.png',
  INTRO2_2: 'page2/2.png',
  INTRO2_3: 'page2/3.png',
  PAGE3_BG: 'page3/BACKGROUND.png',
  PAGE3_TOP_BANNER: 'page3/TOP_BANNER.png',
  PAGE3_AVATAR: 'page3/AVATAR.png',
  PAGE3_DICE: 'page3/DICE.png',
  PAGE3_EVENT: 'page3/EVENT.png',
  PAGE4_BG: 'page4/BACKGROUND.png',
  PAGE4_LOGO: 'page4/LOGO.png',
  PAGE4_SUPERSPINS: 'page4/SUPERSPINS.png',
  PAGE4_SUPERSPINSLOGOSMALL: 'page4/SUPERSPINSLOGOSMALL.png',
  PAGE4_WHEEL: 'page4/WHEEL.png',
  PAGE4_WHEELBACKGROUND: 'page4/WHEELBACKGROUND.jpg',
  PAGE4_COINS: 'page4/COINS.png',
  PAGE4_TOP_BANNER_AFTER: 'page4/TOP_BANNER_AFTER.png',
  PAGE5_1: 'page5/1.png',
  PAGE5_2: 'page5/2.png',
  PAGE5_3: 'page5/3.png',
  PAGE5_4: 'page5/4.png',
  PAGE5_5: 'page5/5.png',
  PAGE6_LONG_BACKGROUND: 'page6/LONG_BACKGROUND.png',
  PAGE6_BOTTOM_BANNER: 'page6/BOTTOM_BANNER.png',
  PAGE6_CHAR: 'page6/char.png',
  PAGE6_CHAT_1: 'page6/chat_1.png',
  PAGE6_CHAT_2: 'page6/chat_2.png',
  PAGE6_CHAT_3: 'page6/chat_3.png',
  PAGE6_TOKEN_SHOP: 'page6/token_shop.png',
  PAGE7_LONG_BACKGROUND_SHOP: 'page7/LONG_BACKGROUND_SHOP.png',
  PAGE7_SHOP_1: 'page7/shop_1.png',
  PAGE7_SHOP_2: 'page7/shop_2.png',
  PAGE10_FLAME: 'page10/flame.png',
  PAGE10_CHAT_1: 'page10/chat_1.png',
  PAGE10_CHAT_2: 'page10/chat_2.png',
  PAGE11_LK_BACKGROUND: 'page11/lk_background.png',
  PAGE11_LK_CHAR: 'page11/lk_char.png',
  PAGE11_LK_CHAT_1: 'page11/lk_chat_1.png',
  PAGE11_LK_CHAT_2: 'page11/lk_chat_2.png',
  BANNER_NO_0: 'topbanners/no_0.png',
  BANNER_NO_1: 'topbanners/no_1.png',
  BANNER_NO_2: 'topbanners/no_2.png',
  BANNER_NO_3: 'topbanners/no_3.png',
  BANNER_NO_4: 'topbanners/no_4.png',
  BANNER_NO_5: 'topbanners/no_5.png',
  BANNER_NO_25: 'topbanners/no_25.png',
  BANNER_NO_26: 'topbanners/no_26.png',
  BANNER_NO_27: 'topbanners/no_27.png',
  BANNER_NO_28: 'topbanners/no_28.png',
  BANNER_NO_29: 'topbanners/no_29.png',
  BANNER_NO_30: 'topbanners/no_30.png',
  COIN_COLLECT: 'topbanners/coin_collect.png',
} as const;

console.log('[ASSETS] Total assets loaded:', Object.keys(ASSETS).length);
console.log('[ASSETS] Banner assets:', Object.keys(ASSETS).filter(k => k.startsWith('BANNER')));

export type AssetKey = keyof typeof ASSETS;
